# Generated by Django 6.1.1 on 2026-09-20 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_admission_date_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('admission_number', models.CharField(db_index=True, max_length=50)),
                ('grade_or_program', models.CharField(blank=True, default='', max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('permanently_rejected', 'Permanently Rejected')], db_index=True, default='pending', max_length=30)),
                ('last_requested_at', models.DateTimeField(auto_now_add=True)),
                ('re_request_count', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registration_requests', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registration_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_registration_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='student_reg_tenant__61eb1c_idx'), models.Index(fields=['email', 'tenant'], name='student_reg_email_4c08e6_idx'), models.Index(fields=['admission_number', 'tenant'], name='student_reg_admissi_db88f7_idx')],
            },
        ),
    ]
