"""
Gemini AI Integration Service.
Provides real-time multi-turn tutoring and study note generation
via the official Google Gemini API (gemini-2.5-flash / gemini-1.5-flash).
NO mock data is returned; only real Gemini responses.
"""
import json
import logging
import urllib.request
import urllib.error
from django.conf import settings

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = (
    "You are OMNI AI Tutor, a friendly, highly intelligent, and pedagogical academic assistant "
    "designed for students and educators in the OMNI Educational SaaS platform. "
    "Your mission is to help students learn effectively, break down complex concepts into simple steps, "
    "encourage critical thinking, provide practice problems, and help students succeed academically. "
    "Format your answers with clean markdown: use bold text, bullet points, headers, and code blocks where helpful."
)


def call_gemini_api(prompt: str, subject: str = "", history: list = None, temperature: float = 0.7) -> dict:
    """
    Executes a prompt against the Google Gemini generateContent REST API.
    Returns live API response or descriptive error if unconfigured/failed.
    """
    api_key = getattr(settings, "GEMINI_API_KEY", "") or ""
    model = getattr(settings, "GEMINI_MODEL", "gemini-2.5-flash") or "gemini-2.5-flash"

    # Contextualize subject
    context_prefix = f"[Academic Subject: {subject}]\n" if subject else ""
    full_prompt = f"{context_prefix}{prompt}"

    if not api_key or api_key.strip() in ("", "your_gemini_api_key_here", "None"):
        logger.warning("GEMINI_API_KEY is not configured in backend settings.")
        return {
            "success": False,
            "is_live_ai": False,
            "error": "GEMINI_API_KEY is not configured in OmniEducationalManagementBackend/.env. Please configure a valid Google Gemini API key.",
            "response": "⚠️ **Google Gemini API Key Required**\n\nThe Google Gemini API key has not been configured in your backend `.env` file (`GEMINI_API_KEY`). Please add your Gemini API key to start real-time tutoring with Google Gemini.",
        }

    # Prepare Gemini API request payload
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"

    contents = []

    # Include prior history if provided
    if history and isinstance(history, list):
        for msg in history[-6:]:
            role = "user" if msg.get("role") in ("user", "student") else "model"
            text = msg.get("content") or msg.get("text", "")
            if text:
                contents.append({"role": role, "parts": [{"text": text}]})

    # Add current prompt
    contents.append({"role": "user", "parts": [{"text": full_prompt}]})

    payload = {
        "contents": contents,
        "systemInstruction": {
            "parts": [{"text": SYSTEM_PROMPT}]
        },
        "generationConfig": {
            "temperature": temperature,
            "maxOutputTokens": 1500,
        },
    }

    req_data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=req_data,
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            result_bytes = response.read()
            result_json = json.loads(result_bytes.decode("utf-8"))

            candidates = result_json.get("candidates", [])
            if candidates and "content" in candidates[0]:
                parts = candidates[0]["content"].get("parts", [])
                text_response = "".join(part.get("text", "") for part in parts)
                return {
                    "success": True,
                    "is_live_ai": True,
                    "response": text_response,
                    "model": model,
                }
            else:
                return {
                    "success": False,
                    "is_live_ai": False,
                    "error": "No response text generated by Gemini.",
                    "response": "Gemini API returned an empty response. Please retry with a more detailed question.",
                }
    except urllib.error.HTTPError as e:
        error_content = e.read().decode("utf-8", errors="ignore")
        logger.error(f"Gemini API HTTPError {e.code}: {error_content}")
        # Try fallback model if 2.5-flash isn't available
        if "not found" in error_content.lower() and model != "gemini-1.5-flash":
            return call_gemini_fallback_model(prompt, subject, history, api_key)

        return {
            "success": False,
            "is_live_ai": False,
            "error": f"Gemini API returned HTTP {e.code}: {error_content}",
            "response": f"Gemini API error ({e.code}): {error_content}",
        }
    except Exception as ex:
        logger.exception("Unexpected error communicating with Gemini API")
        return {
            "success": False,
            "is_live_ai": False,
            "error": str(ex),
            "response": f"Unable to reach Google Gemini API: {str(ex)}",
        }


def call_gemini_fallback_model(prompt: str, subject: str, history: list, api_key: str):
    """Fallback to gemini-1.5-flash if 2.5 isn't available."""
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
    payload = {
        "contents": [{"role": "user", "parts": [{"text": prompt}]}],
        "systemInstruction": {"parts": [{"text": SYSTEM_PROMPT}]}
    }
    req_data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=req_data, headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            text = data["candidates"][0]["content"]["parts"][0]["text"]
            return {"success": True, "is_live_ai": True, "response": text, "model": "gemini-1.5-flash"}
    except Exception as e:
        return {
            "success": False,
            "is_live_ai": False,
            "error": str(e),
            "response": f"Gemini API error: {str(e)}",
        }
